# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/GUI/runSlurm/runslurmdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RunSlurmDialog(object):
    def setupUi(self, RunSlurmDialog):
        RunSlurmDialog.setObjectName("RunSlurmDialog")
        RunSlurmDialog.resize(291, 199)
        self.line_2 = QtWidgets.QFrame(RunSlurmDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_cancel = QtWidgets.QPushButton(RunSlurmDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(160, 160, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_ok = QtWidgets.QPushButton(RunSlurmDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(40, 160, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label = QtWidgets.QLabel(RunSlurmDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(RunSlurmDialog)
        self.line.setGeometry(QtCore.QRect(130, 10, 151, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(RunSlurmDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.comboBox = QtWidgets.QComboBox(RunSlurmDialog)
        self.comboBox.setGeometry(QtCore.QRect(171, 110, 94, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.spinBox_nodes = QtWidgets.QSpinBox(RunSlurmDialog)
        self.spinBox_nodes.setGeometry(QtCore.QRect(171, 40, 61, 27))
        self.spinBox_nodes.setMinimum(1)
        self.spinBox_nodes.setMaximum(10000)
        self.spinBox_nodes.setObjectName("spinBox_nodes")
        self.label_2 = QtWidgets.QLabel(RunSlurmDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 43, 121, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.spinBox_ppn = QtWidgets.QSpinBox(RunSlurmDialog)
        self.spinBox_ppn.setGeometry(QtCore.QRect(171, 74, 61, 27))
        self.spinBox_ppn.setMinimum(1)
        self.spinBox_ppn.setMaximum(1024)
        self.spinBox_ppn.setObjectName("spinBox_ppn")
        self.label_4 = QtWidgets.QLabel(RunSlurmDialog)
        self.label_4.setGeometry(QtCore.QRect(19, 110, 141, 27))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(RunSlurmDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 141, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(RunSlurmDialog)
        QtCore.QMetaObject.connectSlotsByName(RunSlurmDialog)

    def retranslateUi(self, RunSlurmDialog):
        _translate = QtCore.QCoreApplication.translate
        RunSlurmDialog.setWindowTitle(_translate("RunSlurmDialog", "Slurm Run Parameters"))
        self.pushButton_cancel.setText(_translate("RunSlurmDialog", "Cancel"))
        self.pushButton_ok.setText(_translate("RunSlurmDialog", "Ok"))
        self.label.setText(_translate("RunSlurmDialog", "Run with Slurm"))
        self.comboBox.setCurrentText(_translate("RunSlurmDialog", "00:30:00"))
        self.comboBox.setItemText(0, _translate("RunSlurmDialog", "00:30:00"))
        self.comboBox.setItemText(1, _translate("RunSlurmDialog", "01:00:00"))
        self.comboBox.setItemText(2, _translate("RunSlurmDialog", "02:00:00"))
        self.comboBox.setItemText(3, _translate("RunSlurmDialog", "05:00:00"))
        self.comboBox.setItemText(4, _translate("RunSlurmDialog", "08:00:00"))
        self.comboBox.setItemText(5, _translate("RunSlurmDialog", "10:00:00"))
        self.comboBox.setItemText(6, _translate("RunSlurmDialog", "12:00:00"))
        self.comboBox.setItemText(7, _translate("RunSlurmDialog", "15:00:00"))
        self.comboBox.setItemText(8, _translate("RunSlurmDialog", "18:00:00"))
        self.comboBox.setItemText(9, _translate("RunSlurmDialog", "20:00:00"))
        self.comboBox.setItemText(10, _translate("RunSlurmDialog", "24:00:00"))
        self.comboBox.setItemText(11, _translate("RunSlurmDialog", "30:00:00"))
        self.comboBox.setItemText(12, _translate("RunSlurmDialog", "36:00:00"))
        self.comboBox.setItemText(13, _translate("RunSlurmDialog", "40:00:00"))
        self.comboBox.setItemText(14, _translate("RunSlurmDialog", "48:00:00"))
        self.comboBox.setItemText(15, _translate("RunSlurmDialog", "54:00:00"))
        self.comboBox.setItemText(16, _translate("RunSlurmDialog", "60:00:00"))
        self.comboBox.setItemText(17, _translate("RunSlurmDialog", "72:00:00"))
        self.comboBox.setItemText(18, _translate("RunSlurmDialog", "84:00:00"))
        self.comboBox.setItemText(19, _translate("RunSlurmDialog", "96:00:00"))
        self.comboBox.setItemText(20, _translate("RunSlurmDialog", "120:00:00"))
        self.comboBox.setItemText(21, _translate("RunSlurmDialog", "144:00:00"))
        self.comboBox.setItemText(22, _translate("RunSlurmDialog", "168:00:00"))
        self.label_2.setText(_translate("RunSlurmDialog", "Number of nodes"))
        self.label_4.setText(_translate("RunSlurmDialog", "Walltime (HH:mm:ss)"))
        self.label_3.setText(_translate("RunSlurmDialog", "Processors per node"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RunSlurmDialog = QtWidgets.QDialog()
    ui = Ui_RunSlurmDialog()
    ui.setupUi(RunSlurmDialog)
    RunSlurmDialog.show()
    sys.exit(app.exec_())

