# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/UI/ChemFlow/forceFieldMin/mindialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_minDialog(object):
    def setupUi(self, minDialog):
        minDialog.setObjectName("minDialog")
        minDialog.resize(330, 219)
        self.pushButton_cancel = QtWidgets.QPushButton(minDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(184, 180, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label = QtWidgets.QLabel(minDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_ok = QtWidgets.QPushButton(minDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(54, 180, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label_2 = QtWidgets.QLabel(minDialog)
        self.label_2.setGeometry(QtCore.QRect(33, 76, 111, 17))
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(minDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 141))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(minDialog)
        self.line.setGeometry(QtCore.QRect(160, 10, 161, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spinBox_steps = QtWidgets.QSpinBox(minDialog)
        self.spinBox_steps.setGeometry(QtCore.QRect(140, 71, 91, 27))
        self.spinBox_steps.setMinimum(100)
        self.spinBox_steps.setMaximum(100000)
        self.spinBox_steps.setSingleStep(50)
        self.spinBox_steps.setProperty("value", 250)
        self.spinBox_steps.setObjectName("spinBox_steps")
        self.line_3 = QtWidgets.QFrame(minDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 160, 311, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(minDialog)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 108, 121, 20))
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_restraint = QtWidgets.QDoubleSpinBox(minDialog)
        self.doubleSpinBox_restraint.setGeometry(QtCore.QRect(140, 101, 91, 27))
        self.doubleSpinBox_restraint.setMaximum(1000.0)
        self.doubleSpinBox_restraint.setSingleStep(0.2)
        self.doubleSpinBox_restraint.setObjectName("doubleSpinBox_restraint")
        self.label_4 = QtWidgets.QLabel(minDialog)
        self.label_4.setGeometry(QtCore.QRect(240, 110, 71, 17))
        self.label_4.setObjectName("label_4")
        self.comboBox_run = QtWidgets.QComboBox(minDialog)
        self.comboBox_run.setGeometry(QtCore.QRect(140, 40, 121, 25))
        self.comboBox_run.setObjectName("comboBox_run")
        self.comboBox_run.addItem("")
        self.comboBox_run.addItem("")
        self.comboBox_run.addItem("")
        self.comboBox_run.addItem("")
        self.label_5 = QtWidgets.QLabel(minDialog)
        self.label_5.setGeometry(QtCore.QRect(105, 40, 31, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(minDialog)
        self.label_6.setGeometry(QtCore.QRect(301, 105, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(minDialog)
        self.label_7.setGeometry(QtCore.QRect(70, 140, 56, 17))
        self.label_7.setObjectName("label_7")
        self.comboBox_gb = QtWidgets.QComboBox(minDialog)
        self.comboBox_gb.setGeometry(QtCore.QRect(140, 137, 69, 25))
        self.comboBox_gb.setObjectName("comboBox_gb")
        self.comboBox_gb.addItem("")
        self.comboBox_gb.addItem("")
        self.comboBox_gb.addItem("")

        self.retranslateUi(minDialog)
        QtCore.QMetaObject.connectSlotsByName(minDialog)

    def retranslateUi(self, minDialog):
        _translate = QtCore.QCoreApplication.translate
        minDialog.setWindowTitle(_translate("minDialog", "Minimisation Parameters"))
        self.pushButton_cancel.setText(_translate("minDialog", "Cancel"))
        self.label.setText(_translate("minDialog", "Force Field minimisation"))
        self.pushButton_ok.setText(_translate("minDialog", "Ok"))
        self.label_2.setText(_translate("minDialog", "Number of steps"))
        self.label_3.setText(_translate("minDialog", "BackBone restraint"))
        self.label_4.setText(_translate("minDialog", "kcal/mol/Å"))
        self.comboBox_run.setCurrentText(_translate("minDialog", "Sander"))
        self.comboBox_run.setItemText(0, _translate("minDialog", "Minab"))
        self.comboBox_run.setItemText(1, _translate("minDialog", "PMEMD.cuda"))
        self.comboBox_run.setItemText(2, _translate("minDialog", "PMEMD.mpi"))
        self.comboBox_run.setItemText(3, _translate("minDialog", "Sander"))
        self.label_5.setText(_translate("minDialog", "Run"))
        self.label_6.setText(_translate("minDialog", "2"))
        self.label_7.setText(_translate("minDialog", "GB model"))
        self.comboBox_gb.setItemText(0, _translate("minDialog", "1"))
        self.comboBox_gb.setItemText(1, _translate("minDialog", "5"))
        self.comboBox_gb.setItemText(2, _translate("minDialog", "8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    minDialog = QtWidgets.QDialog()
    ui = Ui_minDialog()
    ui.setupUi(minDialog)
    minDialog.show()
    sys.exit(app.exec_())

