# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/UI/ChemFlow/dockPlants/dockplantsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dockPlantsDialog(object):
    def setupUi(self, dockPlantsDialog):
        dockPlantsDialog.setObjectName("dockPlantsDialog")
        dockPlantsDialog.resize(513, 352)
        self.label_2 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 41, 26))
        self.label_2.setObjectName("label_2")
        self.label_exec = QtWidgets.QLabel(dockPlantsDialog)
        self.label_exec.setGeometry(QtCore.QRect(20, 40, 121, 20))
        self.label_exec.setObjectName("label_exec")
        self.pushButton_cancel = QtWidgets.QPushButton(dockPlantsDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(280, 310, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_6 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 41, 26))
        self.label_6.setObjectName("label_6")
        self.line_3 = QtWidgets.QFrame(dockPlantsDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 290, 491, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_5 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 41, 26))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(dockPlantsDialog)
        self.line.setGeometry(QtCore.QRect(150, 10, 351, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_SporesExec = QtWidgets.QPushButton(dockPlantsDialog)
        self.pushButton_SporesExec.setGeometry(QtCore.QRect(400, 70, 86, 21))
        self.pushButton_SporesExec.setObjectName("pushButton_SporesExec")
        self.textBrowser_SporesExec = QtWidgets.QTextBrowser(dockPlantsDialog)
        self.textBrowser_SporesExec.setGeometry(QtCore.QRect(138, 70, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_SporesExec.setFont(font)
        self.textBrowser_SporesExec.setObjectName("textBrowser_SporesExec")
        self.doubleSpinBox_cz = QtWidgets.QDoubleSpinBox(dockPlantsDialog)
        self.doubleSpinBox_cz.setGeometry(QtCore.QRect(80, 200, 131, 27))
        self.doubleSpinBox_cz.setDecimals(3)
        self.doubleSpinBox_cz.setMinimum(-10000.0)
        self.doubleSpinBox_cz.setMaximum(10000.0)
        self.doubleSpinBox_cz.setObjectName("doubleSpinBox_cz")
        self.label_exec_2 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_exec_2.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.label_exec_2.setObjectName("label_exec_2")
        self.textBrowser_PlantsExec = QtWidgets.QTextBrowser(dockPlantsDialog)
        self.textBrowser_PlantsExec.setGeometry(QtCore.QRect(138, 40, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_PlantsExec.setFont(font)
        self.textBrowser_PlantsExec.setObjectName("textBrowser_PlantsExec")
        self.label = QtWidgets.QLabel(dockPlantsDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_ok = QtWidgets.QPushButton(dockPlantsDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(150, 310, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.line_2 = QtWidgets.QFrame(dockPlantsDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 271))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.doubleSpinBox_cy = QtWidgets.QDoubleSpinBox(dockPlantsDialog)
        self.doubleSpinBox_cy.setGeometry(QtCore.QRect(80, 170, 131, 27))
        self.doubleSpinBox_cy.setDecimals(3)
        self.doubleSpinBox_cy.setMinimum(-10000.0)
        self.doubleSpinBox_cy.setMaximum(10000.0)
        self.doubleSpinBox_cy.setObjectName("doubleSpinBox_cy")
        self.line_4 = QtWidgets.QFrame(dockPlantsDialog)
        self.line_4.setGeometry(QtCore.QRect(210, 110, 20, 148))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_PlantsExec = QtWidgets.QPushButton(dockPlantsDialog)
        self.pushButton_PlantsExec.setGeometry(QtCore.QRect(400, 40, 86, 21))
        self.pushButton_PlantsExec.setObjectName("pushButton_PlantsExec")
        self.doubleSpinBox_cx = QtWidgets.QDoubleSpinBox(dockPlantsDialog)
        self.doubleSpinBox_cx.setGeometry(QtCore.QRect(80, 140, 131, 27))
        self.doubleSpinBox_cx.setDecimals(3)
        self.doubleSpinBox_cx.setMinimum(-10000.0)
        self.doubleSpinBox_cx.setMaximum(10000.0)
        self.doubleSpinBox_cx.setObjectName("doubleSpinBox_cx")
        self.label_3 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_3.setGeometry(QtCore.QRect(90, 110, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_radius = QtWidgets.QDoubleSpinBox(dockPlantsDialog)
        self.doubleSpinBox_radius.setGeometry(QtCore.QRect(80, 230, 131, 27))
        self.doubleSpinBox_radius.setDecimals(3)
        self.doubleSpinBox_radius.setMinimum(1.0)
        self.doubleSpinBox_radius.setMaximum(10000.0)
        self.doubleSpinBox_radius.setProperty("value", 10.0)
        self.doubleSpinBox_radius.setObjectName("doubleSpinBox_radius")
        self.label_10 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_10.setGeometry(QtCore.QRect(30, 230, 41, 26))
        self.label_10.setObjectName("label_10")
        self.comboBox_scoringFunction = QtWidgets.QComboBox(dockPlantsDialog)
        self.comboBox_scoringFunction.setGeometry(QtCore.QRect(370, 110, 131, 21))
        self.comboBox_scoringFunction.setObjectName("comboBox_scoringFunction")
        self.comboBox_scoringFunction.addItem("")
        self.comboBox_scoringFunction.addItem("")
        self.comboBox_scoringFunction.addItem("")
        self.label_4 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_4.setGeometry(QtCore.QRect(260, 110, 111, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_water = QtWidgets.QPushButton(dockPlantsDialog)
        self.pushButton_water.setGeometry(QtCore.QRect(250, 266, 86, 21))
        self.pushButton_water.setObjectName("pushButton_water")
        self.checkBox_water = QtWidgets.QCheckBox(dockPlantsDialog)
        self.checkBox_water.setGeometry(QtCore.QRect(30, 260, 221, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_water.sizePolicy().hasHeightForWidth())
        self.checkBox_water.setSizePolicy(sizePolicy)
        self.checkBox_water.setObjectName("checkBox_water")
        self.comboBox_searchSpeed = QtWidgets.QComboBox(dockPlantsDialog)
        self.comboBox_searchSpeed.setGeometry(QtCore.QRect(370, 138, 131, 21))
        self.comboBox_searchSpeed.setObjectName("comboBox_searchSpeed")
        self.comboBox_searchSpeed.addItem("")
        self.comboBox_searchSpeed.addItem("")
        self.comboBox_searchSpeed.addItem("")
        self.label_8 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_8.setGeometry(QtCore.QRect(280, 140, 91, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_9.setGeometry(QtCore.QRect(270, 168, 101, 20))
        self.label_9.setObjectName("label_9")
        self.spinBox_ants = QtWidgets.QSpinBox(dockPlantsDialog)
        self.spinBox_ants.setGeometry(QtCore.QRect(370, 164, 70, 27))
        self.spinBox_ants.setMinimum(1)
        self.spinBox_ants.setMaximum(1000)
        self.spinBox_ants.setProperty("value", 20)
        self.spinBox_ants.setObjectName("spinBox_ants")
        self.doubleSpinBox_evaporationRate = QtWidgets.QDoubleSpinBox(dockPlantsDialog)
        self.doubleSpinBox_evaporationRate.setGeometry(QtCore.QRect(370, 196, 70, 27))
        self.doubleSpinBox_evaporationRate.setMaximum(1.0)
        self.doubleSpinBox_evaporationRate.setProperty("value", 0.15)
        self.doubleSpinBox_evaporationRate.setObjectName("doubleSpinBox_evaporationRate")
        self.label_11 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_11.setGeometry(QtCore.QRect(265, 200, 101, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(dockPlantsDialog)
        self.label_12.setGeometry(QtCore.QRect(230, 232, 137, 20))
        self.label_12.setObjectName("label_12")
        self.doubleSpinBox_iterationScaling = QtWidgets.QDoubleSpinBox(dockPlantsDialog)
        self.doubleSpinBox_iterationScaling.setGeometry(QtCore.QRect(370, 228, 70, 27))
        self.doubleSpinBox_iterationScaling.setMaximum(1000.0)
        self.doubleSpinBox_iterationScaling.setSingleStep(0.5)
        self.doubleSpinBox_iterationScaling.setProperty("value", 1.0)
        self.doubleSpinBox_iterationScaling.setObjectName("doubleSpinBox_iterationScaling")

        self.retranslateUi(dockPlantsDialog)
        QtCore.QMetaObject.connectSlotsByName(dockPlantsDialog)

    def retranslateUi(self, dockPlantsDialog):
        _translate = QtCore.QCoreApplication.translate
        dockPlantsDialog.setWindowTitle(_translate("dockPlantsDialog", "PLANTS Docking Parameters"))
        self.label_2.setText(_translate("dockPlantsDialog", "X"))
        self.label_exec.setText(_translate("dockPlantsDialog", "PLANTS Executable"))
        self.pushButton_cancel.setText(_translate("dockPlantsDialog", "Cancel"))
        self.label_6.setText(_translate("dockPlantsDialog", "Z"))
        self.label_5.setText(_translate("dockPlantsDialog", "Y"))
        self.pushButton_SporesExec.setToolTip(_translate("dockPlantsDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.pushButton_SporesExec.setText(_translate("dockPlantsDialog", "Browse"))
        self.textBrowser_SporesExec.setToolTip(_translate("dockPlantsDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.label_exec_2.setText(_translate("dockPlantsDialog", "SPORES Executable"))
        self.label.setText(_translate("dockPlantsDialog", "Docking with PLANTS"))
        self.pushButton_ok.setText(_translate("dockPlantsDialog", "Ok"))
        self.pushButton_PlantsExec.setText(_translate("dockPlantsDialog", "Browse"))
        self.label_3.setText(_translate("dockPlantsDialog", "Binding Site"))
        self.label_10.setText(_translate("dockPlantsDialog", "Radius"))
        self.comboBox_scoringFunction.setToolTip(_translate("dockPlantsDialog", "<html><head/><body><p>- plp95: Piecewise Linear Potential from Gehlhaar DK et al</p><p>- plp: PLANTS version of the Piecewise Linear Potential</p><p>- chemplp: PLANTS version of the Piecewise Linear Potential implementing GOLD\'s terms</p></body></html>"))
        self.comboBox_scoringFunction.setItemText(0, _translate("dockPlantsDialog", "chemplp"))
        self.comboBox_scoringFunction.setItemText(1, _translate("dockPlantsDialog", "plp"))
        self.comboBox_scoringFunction.setItemText(2, _translate("dockPlantsDialog", "plp95"))
        self.label_4.setText(_translate("dockPlantsDialog", "Scoring Function"))
        self.pushButton_water.setText(_translate("dockPlantsDialog", "Configure"))
        self.checkBox_water.setText(_translate("dockPlantsDialog", "Include structural water molecule"))
        self.comboBox_searchSpeed.setToolTip(_translate("dockPlantsDialog", "<html><head/><body><p><span style=\" font-style:italic;\">- speed1</span>: highest reliability but slowest setting</p><p><span style=\" font-style:italic;\">- speed4</span>: 4 times faster than speed1 but modest reliability</p></body></html>"))
        self.comboBox_searchSpeed.setItemText(0, _translate("dockPlantsDialog", "speed1"))
        self.comboBox_searchSpeed.setItemText(1, _translate("dockPlantsDialog", "speed2"))
        self.comboBox_searchSpeed.setItemText(2, _translate("dockPlantsDialog", "speed4"))
        self.label_8.setText(_translate("dockPlantsDialog", "Search speed"))
        self.label_9.setText(_translate("dockPlantsDialog", "Number of ants"))
        self.spinBox_ants.setToolTip(_translate("dockPlantsDialog", "<html><head/><body><p>Default: 20</p></body></html>"))
        self.doubleSpinBox_evaporationRate.setToolTip(_translate("dockPlantsDialog", "<html><head/><body><p>Pheromone evaporation rate. Higher rate usually leads to faster convergency.</p><p>Default: 0,15</p></body></html>"))
        self.label_11.setText(_translate("dockPlantsDialog", "Evaporation rate"))
        self.label_12.setText(_translate("dockPlantsDialog", "Iteration scaling factor"))
        self.doubleSpinBox_iterationScaling.setToolTip(_translate("dockPlantsDialog", "<html><head/><body><p>Multiplies the number of iterations done by the ACO algorithm. Used to tune the tradeoff between computation time and solution quality.</p><p>Default: 1,0</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dockPlantsDialog = QtWidgets.QDialog()
    ui = Ui_dockPlantsDialog()
    ui.setupUi(dockPlantsDialog)
    dockPlantsDialog.show()
    sys.exit(app.exec_())

