# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/UI/ChemFlow/waterPlants/waterplantsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_waterPlantsDialog(object):
    def setupUi(self, waterPlantsDialog):
        waterPlantsDialog.setObjectName("waterPlantsDialog")
        waterPlantsDialog.resize(454, 239)
        self.label_5 = QtWidgets.QLabel(waterPlantsDialog)
        self.label_5.setGeometry(QtCore.QRect(74, 87, 41, 26))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(waterPlantsDialog)
        self.label_2.setGeometry(QtCore.QRect(74, 57, 41, 26))
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(waterPlantsDialog)
        self.label_10.setGeometry(QtCore.QRect(64, 147, 41, 26))
        self.label_10.setObjectName("label_10")
        self.doubleSpinBox_cy = QtWidgets.QDoubleSpinBox(waterPlantsDialog)
        self.doubleSpinBox_cy.setGeometry(QtCore.QRect(114, 87, 131, 27))
        self.doubleSpinBox_cy.setDecimals(3)
        self.doubleSpinBox_cy.setMinimum(-10000.0)
        self.doubleSpinBox_cy.setMaximum(10000.0)
        self.doubleSpinBox_cy.setObjectName("doubleSpinBox_cy")
        self.doubleSpinBox_cx = QtWidgets.QDoubleSpinBox(waterPlantsDialog)
        self.doubleSpinBox_cx.setGeometry(QtCore.QRect(114, 57, 131, 27))
        self.doubleSpinBox_cx.setDecimals(3)
        self.doubleSpinBox_cx.setMinimum(-10000.0)
        self.doubleSpinBox_cx.setMaximum(10000.0)
        self.doubleSpinBox_cx.setObjectName("doubleSpinBox_cx")
        self.doubleSpinBox_radius = QtWidgets.QDoubleSpinBox(waterPlantsDialog)
        self.doubleSpinBox_radius.setGeometry(QtCore.QRect(114, 147, 131, 27))
        self.doubleSpinBox_radius.setDecimals(3)
        self.doubleSpinBox_radius.setMinimum(0.0)
        self.doubleSpinBox_radius.setMaximum(10000.0)
        self.doubleSpinBox_radius.setObjectName("doubleSpinBox_radius")
        self.doubleSpinBox_cz = QtWidgets.QDoubleSpinBox(waterPlantsDialog)
        self.doubleSpinBox_cz.setGeometry(QtCore.QRect(114, 117, 131, 27))
        self.doubleSpinBox_cz.setDecimals(3)
        self.doubleSpinBox_cz.setMinimum(-10000.0)
        self.doubleSpinBox_cz.setMaximum(10000.0)
        self.doubleSpinBox_cz.setObjectName("doubleSpinBox_cz")
        self.label_6 = QtWidgets.QLabel(waterPlantsDialog)
        self.label_6.setGeometry(QtCore.QRect(74, 117, 41, 26))
        self.label_6.setObjectName("label_6")
        self.pushButton_cancel = QtWidgets.QPushButton(waterPlantsDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(250, 197, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.line_2 = QtWidgets.QFrame(waterPlantsDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 27, 20, 161))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(waterPlantsDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 177, 431, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_ok = QtWidgets.QPushButton(waterPlantsDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(120, 197, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label = QtWidgets.QLabel(waterPlantsDialog)
        self.label.setGeometry(QtCore.QRect(10, 7, 141, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(waterPlantsDialog)
        self.line.setGeometry(QtCore.QRect(140, 7, 301, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser_water = QtWidgets.QTextBrowser(waterPlantsDialog)
        self.textBrowser_water.setGeometry(QtCore.QRect(115, 30, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_water.setFont(font)
        self.textBrowser_water.setObjectName("textBrowser_water")
        self.label_rec = QtWidgets.QLabel(waterPlantsDialog)
        self.label_rec.setGeometry(QtCore.QRect(20, 30, 91, 20))
        self.label_rec.setObjectName("label_rec")
        self.pushButton_water = QtWidgets.QPushButton(waterPlantsDialog)
        self.pushButton_water.setGeometry(QtCore.QRect(360, 30, 86, 21))
        self.pushButton_water.setObjectName("pushButton_water")

        self.retranslateUi(waterPlantsDialog)
        QtCore.QMetaObject.connectSlotsByName(waterPlantsDialog)

    def retranslateUi(self, waterPlantsDialog):
        _translate = QtCore.QCoreApplication.translate
        waterPlantsDialog.setWindowTitle(_translate("waterPlantsDialog", "PLANTS water parameters"))
        self.label_5.setText(_translate("waterPlantsDialog", "Y"))
        self.label_2.setText(_translate("waterPlantsDialog", "X"))
        self.label_10.setText(_translate("waterPlantsDialog", "Radius"))
        self.doubleSpinBox_cy.setToolTip(_translate("waterPlantsDialog", "<html><head/><body><p>Sphere inside which the water molecule is allowed to move. If the water molecule is displaced by a ligand and moved outside the sphere, the water molecule has no score contribution.</p></body></html>"))
        self.doubleSpinBox_cx.setToolTip(_translate("waterPlantsDialog", "<html><head/><body><p>Sphere inside which the water molecule is allowed to move. If the water molecule is displaced by a ligand and moved outside the sphere, the water molecule has no score contribution.</p></body></html>"))
        self.doubleSpinBox_radius.setToolTip(_translate("waterPlantsDialog", "<html><head/><body><p>Sphere inside which the water molecule is allowed to move. If the water molecule is displaced by a ligand and moved outside the sphere, the water molecule has no score contribution.</p></body></html>"))
        self.doubleSpinBox_cz.setToolTip(_translate("waterPlantsDialog", "<html><head/><body><p>Sphere inside which the water molecule is allowed to move. If the water molecule is displaced by a ligand and moved outside the sphere, the water molecule has no score contribution.</p></body></html>"))
        self.label_6.setText(_translate("waterPlantsDialog", "Z"))
        self.pushButton_cancel.setText(_translate("waterPlantsDialog", "Cancel"))
        self.pushButton_ok.setText(_translate("waterPlantsDialog", "Ok"))
        self.label.setText(_translate("waterPlantsDialog", "PLANTS with water"))
        self.textBrowser_water.setToolTip(_translate("waterPlantsDialog", "<html><head/><body><p>MOL2 file containing a single water molecule.</p><p>Position and orientation is arbitrary.</p></body></html>"))
        self.label_rec.setText(_translate("waterPlantsDialog", "Water molecule"))
        self.pushButton_water.setToolTip(_translate("waterPlantsDialog", "<html><head/><body><p>MOL2 file containing a single water molecule.</p><p>Position and orientation is arbitrary.</p></body></html>"))
        self.pushButton_water.setText(_translate("waterPlantsDialog", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    waterPlantsDialog = QtWidgets.QDialog()
    ui = Ui_waterPlantsDialog()
    ui.setupUi(waterPlantsDialog)
    waterPlantsDialog.show()
    sys.exit(app.exec_())

