# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/GUI/dockVina/dockvinadialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dockVinaDialog(object):
    def setupUi(self, dockVinaDialog):
        dockVinaDialog.setObjectName("dockVinaDialog")
        dockVinaDialog.resize(484, 329)
        self.line = QtWidgets.QFrame(dockVinaDialog)
        self.line.setGeometry(QtCore.QRect(210, 10, 261, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_ok = QtWidgets.QPushButton(dockVinaDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(132, 290, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.line_2 = QtWidgets.QFrame(dockVinaDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 251))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(dockVinaDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(dockVinaDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 270, 461, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_cancel = QtWidgets.QPushButton(dockVinaDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(262, 290, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_exec = QtWidgets.QPushButton(dockVinaDialog)
        self.pushButton_exec.setGeometry(QtCore.QRect(382, 40, 86, 21))
        self.pushButton_exec.setObjectName("pushButton_exec")
        self.label_exec = QtWidgets.QLabel(dockVinaDialog)
        self.label_exec.setGeometry(QtCore.QRect(20, 40, 121, 20))
        self.label_exec.setObjectName("label_exec")
        self.textBrowser_vinaExec = QtWidgets.QTextBrowser(dockVinaDialog)
        self.textBrowser_vinaExec.setGeometry(QtCore.QRect(140, 40, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_vinaExec.setFont(font)
        self.textBrowser_vinaExec.setObjectName("textBrowser_vinaExec")
        self.label_2 = QtWidgets.QLabel(dockVinaDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 41, 26))
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox_cx = QtWidgets.QDoubleSpinBox(dockVinaDialog)
        self.doubleSpinBox_cx.setGeometry(QtCore.QRect(80, 180, 131, 27))
        self.doubleSpinBox_cx.setDecimals(3)
        self.doubleSpinBox_cx.setMinimum(-10000.0)
        self.doubleSpinBox_cx.setMaximum(10000.0)
        self.doubleSpinBox_cx.setObjectName("doubleSpinBox_cx")
        self.line_4 = QtWidgets.QFrame(dockVinaDialog)
        self.line_4.setGeometry(QtCore.QRect(230, 150, 20, 131))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_5 = QtWidgets.QLabel(dockVinaDialog)
        self.label_5.setGeometry(QtCore.QRect(40, 210, 41, 26))
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_cy = QtWidgets.QDoubleSpinBox(dockVinaDialog)
        self.doubleSpinBox_cy.setGeometry(QtCore.QRect(80, 210, 131, 27))
        self.doubleSpinBox_cy.setDecimals(3)
        self.doubleSpinBox_cy.setMinimum(-10000.0)
        self.doubleSpinBox_cy.setMaximum(10000.0)
        self.doubleSpinBox_cy.setObjectName("doubleSpinBox_cy")
        self.label_6 = QtWidgets.QLabel(dockVinaDialog)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 41, 26))
        self.label_6.setObjectName("label_6")
        self.doubleSpinBox_cz = QtWidgets.QDoubleSpinBox(dockVinaDialog)
        self.doubleSpinBox_cz.setGeometry(QtCore.QRect(80, 240, 131, 27))
        self.doubleSpinBox_cz.setDecimals(3)
        self.doubleSpinBox_cz.setMinimum(-10000.0)
        self.doubleSpinBox_cz.setMaximum(10000.0)
        self.doubleSpinBox_cz.setObjectName("doubleSpinBox_cz")
        self.label_7 = QtWidgets.QLabel(dockVinaDialog)
        self.label_7.setGeometry(QtCore.QRect(270, 180, 41, 26))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(dockVinaDialog)
        self.label_8.setGeometry(QtCore.QRect(270, 240, 41, 26))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(dockVinaDialog)
        self.label_9.setGeometry(QtCore.QRect(270, 210, 41, 26))
        self.label_9.setObjectName("label_9")
        self.label_exec_2 = QtWidgets.QLabel(dockVinaDialog)
        self.label_exec_2.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.label_exec_2.setObjectName("label_exec_2")
        self.pushButton_adtFolder = QtWidgets.QPushButton(dockVinaDialog)
        self.pushButton_adtFolder.setGeometry(QtCore.QRect(382, 70, 86, 21))
        self.pushButton_adtFolder.setObjectName("pushButton_adtFolder")
        self.textBrowser_adtFolder = QtWidgets.QTextBrowser(dockVinaDialog)
        self.textBrowser_adtFolder.setGeometry(QtCore.QRect(140, 70, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_adtFolder.setFont(font)
        self.textBrowser_adtFolder.setObjectName("textBrowser_adtFolder")
        self.label_3 = QtWidgets.QLabel(dockVinaDialog)
        self.label_3.setGeometry(QtCore.QRect(70, 148, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dockVinaDialog)
        self.label_4.setGeometry(QtCore.QRect(300, 148, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_sx = QtWidgets.QSpinBox(dockVinaDialog)
        self.spinBox_sx.setGeometry(QtCore.QRect(310, 180, 101, 27))
        self.spinBox_sx.setMinimum(1)
        self.spinBox_sx.setMaximum(10000)
        self.spinBox_sx.setProperty("value", 40)
        self.spinBox_sx.setObjectName("spinBox_sx")
        self.spinBox_sy = QtWidgets.QSpinBox(dockVinaDialog)
        self.spinBox_sy.setGeometry(QtCore.QRect(310, 210, 101, 27))
        self.spinBox_sy.setMinimum(1)
        self.spinBox_sy.setMaximum(10000)
        self.spinBox_sy.setProperty("value", 40)
        self.spinBox_sy.setObjectName("spinBox_sy")
        self.spinBox_sz = QtWidgets.QSpinBox(dockVinaDialog)
        self.spinBox_sz.setGeometry(QtCore.QRect(310, 240, 101, 27))
        self.spinBox_sz.setMinimum(1)
        self.spinBox_sz.setMaximum(10000)
        self.spinBox_sz.setProperty("value", 40)
        self.spinBox_sz.setObjectName("spinBox_sz")
        self.label_10 = QtWidgets.QLabel(dockVinaDialog)
        self.label_10.setGeometry(QtCore.QRect(60, 110, 111, 20))
        self.label_10.setObjectName("label_10")
        self.spinBox_exhaustiveness = QtWidgets.QSpinBox(dockVinaDialog)
        self.spinBox_exhaustiveness.setGeometry(QtCore.QRect(170, 107, 51, 27))
        self.spinBox_exhaustiveness.setMinimum(1)
        self.spinBox_exhaustiveness.setProperty("value", 8)
        self.spinBox_exhaustiveness.setObjectName("spinBox_exhaustiveness")
        self.doubleSpinBox_energyRange = QtWidgets.QDoubleSpinBox(dockVinaDialog)
        self.doubleSpinBox_energyRange.setGeometry(QtCore.QRect(350, 107, 65, 27))
        self.doubleSpinBox_energyRange.setProperty("value", 3.0)
        self.doubleSpinBox_energyRange.setObjectName("doubleSpinBox_energyRange")
        self.label_11 = QtWidgets.QLabel(dockVinaDialog)
        self.label_11.setGeometry(QtCore.QRect(260, 110, 91, 20))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(dockVinaDialog)
        QtCore.QMetaObject.connectSlotsByName(dockVinaDialog)

    def retranslateUi(self, dockVinaDialog):
        _translate = QtCore.QCoreApplication.translate
        dockVinaDialog.setWindowTitle(_translate("dockVinaDialog", "AutoDock Vina Docking Parameters"))
        self.pushButton_ok.setText(_translate("dockVinaDialog", "Ok"))
        self.label.setText(_translate("dockVinaDialog", "Docking with AutoDock Vina"))
        self.pushButton_cancel.setText(_translate("dockVinaDialog", "Cancel"))
        self.pushButton_exec.setText(_translate("dockVinaDialog", "Browse"))
        self.label_exec.setText(_translate("dockVinaDialog", "Vina Executable"))
        self.label_2.setText(_translate("dockVinaDialog", "X"))
        self.label_5.setText(_translate("dockVinaDialog", "Y"))
        self.label_6.setText(_translate("dockVinaDialog", "Z"))
        self.label_7.setText(_translate("dockVinaDialog", "X"))
        self.label_8.setText(_translate("dockVinaDialog", "Z"))
        self.label_9.setText(_translate("dockVinaDialog", "Y"))
        self.label_exec_2.setText(_translate("dockVinaDialog", "AutoDockTools"))
        self.pushButton_adtFolder.setToolTip(_translate("dockVinaDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.pushButton_adtFolder.setText(_translate("dockVinaDialog", "Browse"))
        self.textBrowser_adtFolder.setToolTip(_translate("dockVinaDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.label_3.setText(_translate("dockVinaDialog", "Center of the grid"))
        self.label_4.setText(_translate("dockVinaDialog", "Size of the grid"))
        self.label_10.setText(_translate("dockVinaDialog", "Exhaustiveness"))
        self.doubleSpinBox_energyRange.setToolTip(_translate("dockVinaDialog", "<html><head/><body><p>Maximum energy difference between the best binding mode and the worst one displayed (kcal/mol)</p></body></html>"))
        self.label_11.setText(_translate("dockVinaDialog", "Energy range"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dockVinaDialog = QtWidgets.QDialog()
    ui = Ui_dockVinaDialog()
    ui.setupUi(dockVinaDialog)
    dockVinaDialog.show()
    sys.exit(app.exec_())

