# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/GUI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 543)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton_lig = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_lig.setGeometry(QtCore.QRect(480, 190, 86, 21))
        self.pushButton_lig.setObjectName("pushButton_lig")
        self.label_output = QtWidgets.QLabel(self.centralWidget)
        self.label_output.setGeometry(QtCore.QRect(60, 240, 41, 20))
        self.label_output.setObjectName("label_output")
        self.label_protocol = QtWidgets.QLabel(self.centralWidget)
        self.label_protocol.setGeometry(QtCore.QRect(20, 60, 61, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_protocol.setFont(font)
        self.label_protocol.setObjectName("label_protocol")
        self.comboBox_rescoringSoftware = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_rescoringSoftware.setGeometry(QtCore.QRect(100, 420, 221, 21))
        self.comboBox_rescoringSoftware.setObjectName("comboBox_rescoringSoftware")
        self.comboBox_rescoringSoftware.addItem("")
        self.comboBox_rescoringSoftware.addItem("")
        self.comboBox_rescoringSoftware.addItem("")
        self.label_docking = QtWidgets.QLabel(self.centralWidget)
        self.label_docking.setGeometry(QtCore.QRect(20, 270, 56, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_docking.setFont(font)
        self.label_docking.setObjectName("label_docking")
        self.pushButton_run = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_run.setGeometry(QtCore.QRect(20, 490, 86, 29))
        self.pushButton_run.setObjectName("pushButton_run")
        self.line_13 = QtWidgets.QFrame(self.centralWidget)
        self.line_13.setGeometry(QtCore.QRect(10, 80, 20, 61))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(480, 490, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.textBrowser_rec = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_rec.setGeometry(QtCore.QRect(100, 160, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_rec.setFont(font)
        self.textBrowser_rec.setObjectName("textBrowser_rec")
        self.label_protocolPreset = QtWidgets.QLabel(self.centralWidget)
        self.label_protocolPreset.setGeometry(QtCore.QRect(50, 80, 51, 20))
        self.label_protocolPreset.setObjectName("label_protocolPreset")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(130, 220, 441, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setGeometry(QtCore.QRect(10, 290, 20, 61))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.spinBox_docking = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_docking.setGeometry(QtCore.QRect(100, 310, 61, 31))
        self.spinBox_docking.setMinimum(1)
        self.spinBox_docking.setMaximum(1000)
        self.spinBox_docking.setObjectName("spinBox_docking")
        self.label_runOptions = QtWidgets.QLabel(self.centralWidget)
        self.label_runOptions.setGeometry(QtCore.QRect(65, 110, 41, 20))
        self.label_runOptions.setObjectName("label_runOptions")
        self.label_dockingKeep_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_dockingKeep_2.setGeometry(QtCore.QRect(170, 310, 111, 31))
        self.label_dockingKeep_2.setObjectName("label_dockingKeep_2")
        self.textBrowser_output = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_output.setGeometry(QtCore.QRect(100, 240, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_output.setFont(font)
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 160, 20, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_writeConfig = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_writeConfig.setGeometry(QtCore.QRect(103, 490, 121, 29))
        self.pushButton_writeConfig.setObjectName("pushButton_writeConfig")
        self.comboBox_dockingSoftware = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_dockingSoftware.setGeometry(QtCore.QRect(100, 290, 221, 21))
        self.comboBox_dockingSoftware.setObjectName("comboBox_dockingSoftware")
        self.comboBox_dockingSoftware.addItem("")
        self.comboBox_dockingSoftware.addItem("")
        self.label_lig = QtWidgets.QLabel(self.centralWidget)
        self.label_lig.setGeometry(QtCore.QRect(40, 190, 61, 20))
        self.label_lig.setObjectName("label_lig")
        self.spinBox_rescoring = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_rescoring.setGeometry(QtCore.QRect(100, 440, 61, 31))
        self.spinBox_rescoring.setMinimum(1)
        self.spinBox_rescoring.setMaximum(1000)
        self.spinBox_rescoring.setObjectName("spinBox_rescoring")
        self.label_rescoring = QtWidgets.QLabel(self.centralWidget)
        self.label_rescoring.setGeometry(QtCore.QRect(20, 400, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rescoring.setFont(font)
        self.label_rescoring.setObjectName("label_rescoring")
        self.label_rec = QtWidgets.QLabel(self.centralWidget)
        self.label_rec.setGeometry(QtCore.QRect(40, 160, 61, 20))
        self.label_rec.setObjectName("label_rec")
        self.pushButton_runConfigure = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_runConfigure.setGeometry(QtCore.QRect(330, 110, 86, 21))
        self.pushButton_runConfigure.setObjectName("pushButton_runConfigure")
        self.label_forceFieldMin = QtWidgets.QLabel(self.centralWidget)
        self.label_forceFieldMin.setGeometry(QtCore.QRect(20, 350, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_forceFieldMin.setFont(font)
        self.label_forceFieldMin.setObjectName("label_forceFieldMin")
        self.label_rescoringKeep_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_rescoringKeep_2.setGeometry(QtCore.QRect(170, 440, 121, 31))
        self.label_rescoringKeep_2.setObjectName("label_rescoringKeep_2")
        self.checkBox_lig = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_lig.setGeometry(QtCore.QRect(410, 190, 71, 22))
        self.checkBox_lig.setObjectName("checkBox_lig")
        self.pushButton_dockingConfigure = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_dockingConfigure.setEnabled(True)
        self.pushButton_dockingConfigure.setGeometry(QtCore.QRect(330, 290, 86, 21))
        self.pushButton_dockingConfigure.setObjectName("pushButton_dockingConfigure")
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(80, 270, 491, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_8 = QtWidgets.QFrame(self.centralWidget)
        self.line_8.setGeometry(QtCore.QRect(10, 370, 20, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 240, 21, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setGeometry(QtCore.QRect(170, 350, 401, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_12 = QtWidgets.QFrame(self.centralWidget)
        self.line_12.setGeometry(QtCore.QRect(80, 60, 491, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_outputDir = QtWidgets.QLabel(self.centralWidget)
        self.label_outputDir.setGeometry(QtCore.QRect(20, 220, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_outputDir.setFont(font)
        self.label_outputDir.setObjectName("label_outputDir")
        self.label_rescoringSoftware = QtWidgets.QLabel(self.centralWidget)
        self.label_rescoringSoftware.setGeometry(QtCore.QRect(40, 420, 61, 20))
        self.label_rescoringSoftware.setObjectName("label_rescoringSoftware")
        self.label_dockingKeep = QtWidgets.QLabel(self.centralWidget)
        self.label_dockingKeep.setGeometry(QtCore.QRect(60, 309, 41, 31))
        self.label_dockingKeep.setObjectName("label_dockingKeep")
        self.comboBox_protocolPreset = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_protocolPreset.setGeometry(QtCore.QRect(100, 80, 221, 25))
        self.comboBox_protocolPreset.setObjectName("comboBox_protocolPreset")
        self.comboBox_protocolPreset.addItem("")
        self.comboBox_protocolPreset.addItem("")
        self.comboBox_protocolPreset.addItem("")
        self.line_11 = QtWidgets.QFrame(self.centralWidget)
        self.line_11.setGeometry(QtCore.QRect(20, 470, 551, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.pushButton_rescoringConfigure = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_rescoringConfigure.setGeometry(QtCore.QRect(330, 420, 86, 21))
        self.pushButton_rescoringConfigure.setObjectName("pushButton_rescoringConfigure")
        self.textBrowser_lig = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_lig.setGeometry(QtCore.QRect(100, 190, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_lig.setFont(font)
        self.textBrowser_lig.setObjectName("textBrowser_lig")
        self.label_rescoringKeep = QtWidgets.QLabel(self.centralWidget)
        self.label_rescoringKeep.setGeometry(QtCore.QRect(60, 439, 41, 31))
        self.label_rescoringKeep.setObjectName("label_rescoringKeep")
        self.comboBox_runOptions = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_runOptions.setGeometry(QtCore.QRect(100, 110, 221, 21))
        self.comboBox_runOptions.setObjectName("comboBox_runOptions")
        self.comboBox_runOptions.addItem("")
        self.comboBox_runOptions.addItem("")
        self.comboBox_runOptions.addItem("")
        self.label_logo_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_logo_2.setGeometry(QtCore.QRect(250, 10, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_logo_2.setFont(font)
        self.label_logo_2.setObjectName("label_logo_2")
        self.pushButton_output = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_output.setGeometry(QtCore.QRect(480, 240, 86, 21))
        self.pushButton_output.setObjectName("pushButton_output")
        self.pushButton_readConfig = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_readConfig.setGeometry(QtCore.QRect(221, 490, 121, 29))
        self.pushButton_readConfig.setObjectName("pushButton_readConfig")
        self.line_10 = QtWidgets.QFrame(self.centralWidget)
        self.line_10.setGeometry(QtCore.QRect(10, 420, 20, 61))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(90, 140, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_logo = QtWidgets.QLabel(self.centralWidget)
        self.label_logo.setGeometry(QtCore.QRect(170, 10, 61, 51))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.pushButton_minConfigure = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_minConfigure.setGeometry(QtCore.QRect(190, 372, 86, 21))
        self.pushButton_minConfigure.setObjectName("pushButton_minConfigure")
        self.line_9 = QtWidgets.QFrame(self.centralWidget)
        self.line_9.setGeometry(QtCore.QRect(90, 400, 481, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.pushButton_rec = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_rec.setGeometry(QtCore.QRect(480, 160, 86, 21))
        self.pushButton_rec.setObjectName("pushButton_rec")
        self.label_inputFiles = QtWidgets.QLabel(self.centralWidget)
        self.label_inputFiles.setGeometry(QtCore.QRect(20, 140, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_inputFiles.setFont(font)
        self.label_inputFiles.setObjectName("label_inputFiles")
        self.label_dockingSoftware = QtWidgets.QLabel(self.centralWidget)
        self.label_dockingSoftware.setGeometry(QtCore.QRect(40, 290, 61, 20))
        self.label_dockingSoftware.setObjectName("label_dockingSoftware")
        self.checkBox_min = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_min.setGeometry(QtCore.QRect(30, 371, 151, 22))
        self.checkBox_min.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_min.setObjectName("checkBox_min")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChemFlow"))
        self.pushButton_lig.setText(_translate("MainWindow", "Browse"))
        self.label_output.setText(_translate("MainWindow", "Path"))
        self.label_protocol.setText(_translate("MainWindow", "Protocol"))
        self.comboBox_rescoringSoftware.setItemText(0, _translate("MainWindow", "AutoDock Vina"))
        self.comboBox_rescoringSoftware.setItemText(1, _translate("MainWindow", "MM/PBSA"))
        self.comboBox_rescoringSoftware.setItemText(2, _translate("MainWindow", "PLANTS"))
        self.label_docking.setText(_translate("MainWindow", "Docking"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_protocolPreset.setText(_translate("MainWindow", "Preset"))
        self.label_runOptions.setText(_translate("MainWindow", "Run"))
        self.label_dockingKeep_2.setText(_translate("MainWindow", "pose(s) per ligand"))
        self.pushButton_writeConfig.setText(_translate("MainWindow", "Write config file"))
        self.comboBox_dockingSoftware.setItemText(0, _translate("MainWindow", "AutoDock Vina"))
        self.comboBox_dockingSoftware.setItemText(1, _translate("MainWindow", "PLANTS"))
        self.label_lig.setText(_translate("MainWindow", "Ligand(s)"))
        self.label_rescoring.setText(_translate("MainWindow", "Rescoring"))
        self.label_rec.setText(_translate("MainWindow", "Receptor"))
        self.pushButton_runConfigure.setText(_translate("MainWindow", "Configure"))
        self.label_forceFieldMin.setText(_translate("MainWindow", "Force field minimisation"))
        self.label_rescoringKeep_2.setText(_translate("MainWindow", "pose(s) per ligand"))
        self.checkBox_lig.setText(_translate("MainWindow", "Folder"))
        self.pushButton_dockingConfigure.setText(_translate("MainWindow", "Configure"))
        self.label_outputDir.setText(_translate("MainWindow", "Output directory"))
        self.label_rescoringSoftware.setText(_translate("MainWindow", "Software"))
        self.label_dockingKeep.setText(_translate("MainWindow", "Keep"))
        self.comboBox_protocolPreset.setItemText(0, _translate("MainWindow", "Docking"))
        self.comboBox_protocolPreset.setItemText(1, _translate("MainWindow", "Docking + Rescoring"))
        self.comboBox_protocolPreset.setItemText(2, _translate("MainWindow", "Rescoring"))
        self.pushButton_rescoringConfigure.setText(_translate("MainWindow", "Configure"))
        self.label_rescoringKeep.setText(_translate("MainWindow", "Keep"))
        self.comboBox_runOptions.setItemText(0, _translate("MainWindow", "Locally"))
        self.comboBox_runOptions.setItemText(1, _translate("MainWindow", "PBS"))
        self.comboBox_runOptions.setItemText(2, _translate("MainWindow", "Slurm"))
        self.label_logo_2.setText(_translate("MainWindow", "ChemFlow"))
        self.pushButton_output.setText(_translate("MainWindow", "Browse"))
        self.pushButton_readConfig.setText(_translate("MainWindow", "Read config file"))
        self.pushButton_minConfigure.setText(_translate("MainWindow", "Configure"))
        self.pushButton_rec.setText(_translate("MainWindow", "Browse"))
        self.label_inputFiles.setText(_translate("MainWindow", "Input files"))
        self.label_dockingSoftware.setText(_translate("MainWindow", "Software"))
        self.checkBox_min.setText(_translate("MainWindow", "Minimize the complex "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

