# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/GUI/rescorePlants/rescoreplantsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rescorePlantsDialog(object):
    def setupUi(self, rescorePlantsDialog):
        rescorePlantsDialog.setObjectName("rescorePlantsDialog")
        rescorePlantsDialog.resize(514, 221)
        self.line_3 = QtWidgets.QFrame(rescorePlantsDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 160, 491, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(rescorePlantsDialog)
        self.line.setGeometry(QtCore.QRect(180, 10, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_cancel = QtWidgets.QPushButton(rescorePlantsDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(280, 180, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_ok = QtWidgets.QPushButton(rescorePlantsDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(150, 180, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label = QtWidgets.QLabel(rescorePlantsDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(rescorePlantsDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 141))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_SporesExec = QtWidgets.QPushButton(rescorePlantsDialog)
        self.pushButton_SporesExec.setGeometry(QtCore.QRect(399, 70, 86, 21))
        self.pushButton_SporesExec.setObjectName("pushButton_SporesExec")
        self.textBrowser_PlantsExec = QtWidgets.QTextBrowser(rescorePlantsDialog)
        self.textBrowser_PlantsExec.setGeometry(QtCore.QRect(157, 40, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_PlantsExec.setFont(font)
        self.textBrowser_PlantsExec.setObjectName("textBrowser_PlantsExec")
        self.comboBox_scoringFunction = QtWidgets.QComboBox(rescorePlantsDialog)
        self.comboBox_scoringFunction.setGeometry(QtCore.QRect(156, 105, 106, 24))
        self.comboBox_scoringFunction.setObjectName("comboBox_scoringFunction")
        self.comboBox_scoringFunction.addItem("")
        self.comboBox_scoringFunction.addItem("")
        self.comboBox_scoringFunction.addItem("")
        self.pushButton_PlantsExec = QtWidgets.QPushButton(rescorePlantsDialog)
        self.pushButton_PlantsExec.setGeometry(QtCore.QRect(399, 40, 86, 21))
        self.pushButton_PlantsExec.setObjectName("pushButton_PlantsExec")
        self.textBrowser_SporesExec = QtWidgets.QTextBrowser(rescorePlantsDialog)
        self.textBrowser_SporesExec.setGeometry(QtCore.QRect(157, 70, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_SporesExec.setFont(font)
        self.textBrowser_SporesExec.setObjectName("textBrowser_SporesExec")
        self.label_exec = QtWidgets.QLabel(rescorePlantsDialog)
        self.label_exec.setGeometry(QtCore.QRect(19, 40, 141, 20))
        self.label_exec.setObjectName("label_exec")
        self.label_exec_2 = QtWidgets.QLabel(rescorePlantsDialog)
        self.label_exec_2.setGeometry(QtCore.QRect(19, 70, 141, 20))
        self.label_exec_2.setObjectName("label_exec_2")
        self.checkBox_water = QtWidgets.QCheckBox(rescorePlantsDialog)
        self.checkBox_water.setGeometry(QtCore.QRect(20, 136, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_water.sizePolicy().hasHeightForWidth())
        self.checkBox_water.setSizePolicy(sizePolicy)
        self.checkBox_water.setObjectName("checkBox_water")
        self.pushButton_water = QtWidgets.QPushButton(rescorePlantsDialog)
        self.pushButton_water.setGeometry(QtCore.QRect(260, 140, 86, 23))
        self.pushButton_water.setObjectName("pushButton_water")
        self.label_4 = QtWidgets.QLabel(rescorePlantsDialog)
        self.label_4.setGeometry(QtCore.QRect(9, 106, 121, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(rescorePlantsDialog)
        QtCore.QMetaObject.connectSlotsByName(rescorePlantsDialog)

    def retranslateUi(self, rescorePlantsDialog):
        _translate = QtCore.QCoreApplication.translate
        rescorePlantsDialog.setWindowTitle(_translate("rescorePlantsDialog", "PLANTS Rescoring Parameters"))
        self.pushButton_cancel.setText(_translate("rescorePlantsDialog", "Cancel"))
        self.pushButton_ok.setText(_translate("rescorePlantsDialog", "Ok"))
        self.label.setText(_translate("rescorePlantsDialog", "Rescoring with PLANTS"))
        self.pushButton_SporesExec.setToolTip(_translate("rescorePlantsDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.pushButton_SporesExec.setText(_translate("rescorePlantsDialog", "Browse"))
        self.comboBox_scoringFunction.setToolTip(_translate("rescorePlantsDialog", "<html><head/><body><p>- plp95: Piecewise Linear Potential from Gehlhaar DK et al</p><p>- plp: PLANTS version of the Piecewise Linear Potential</p><p>- chemplp: PLANTS version of the Piecewise Linear Potential implementing GOLD\'s terms</p></body></html>"))
        self.comboBox_scoringFunction.setItemText(0, _translate("rescorePlantsDialog", "chemplp"))
        self.comboBox_scoringFunction.setItemText(1, _translate("rescorePlantsDialog", "plp"))
        self.comboBox_scoringFunction.setItemText(2, _translate("rescorePlantsDialog", "plp95"))
        self.pushButton_PlantsExec.setText(_translate("rescorePlantsDialog", "Browse"))
        self.textBrowser_SporesExec.setToolTip(_translate("rescorePlantsDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.label_exec.setText(_translate("rescorePlantsDialog", "PLANTS Executable"))
        self.label_exec_2.setText(_translate("rescorePlantsDialog", "SPORES Executable"))
        self.checkBox_water.setText(_translate("rescorePlantsDialog", "Include structural water molecule"))
        self.pushButton_water.setText(_translate("rescorePlantsDialog", "Configure"))
        self.label_4.setText(_translate("rescorePlantsDialog", "Scoring Function"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rescorePlantsDialog = QtWidgets.QDialog()
    ui = Ui_rescorePlantsDialog()
    ui.setupUi(rescorePlantsDialog)
    rescorePlantsDialog.show()
    sys.exit(app.exec_())

