# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/UI/ChemFlow/rescoreVina/rescorevinadialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rescoreVinaDialog(object):
    def setupUi(self, rescoreVinaDialog):
        rescoreVinaDialog.setObjectName("rescoreVinaDialog")
        rescoreVinaDialog.resize(479, 289)
        self.line_4 = QtWidgets.QFrame(rescoreVinaDialog)
        self.line_4.setGeometry(QtCore.QRect(230, 110, 20, 131))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_9 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_9.setGeometry(QtCore.QRect(270, 170, 41, 26))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_7.setGeometry(QtCore.QRect(270, 140, 41, 26))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_4.setGeometry(QtCore.QRect(300, 107, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_adtFolder = QtWidgets.QTextBrowser(rescoreVinaDialog)
        self.textBrowser_adtFolder.setGeometry(QtCore.QRect(120, 70, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_adtFolder.setFont(font)
        self.textBrowser_adtFolder.setObjectName("textBrowser_adtFolder")
        self.doubleSpinBox_cx = QtWidgets.QDoubleSpinBox(rescoreVinaDialog)
        self.doubleSpinBox_cx.setGeometry(QtCore.QRect(80, 140, 131, 27))
        self.doubleSpinBox_cx.setDecimals(3)
        self.doubleSpinBox_cx.setMinimum(-10000.0)
        self.doubleSpinBox_cx.setMaximum(10000.0)
        self.doubleSpinBox_cx.setObjectName("doubleSpinBox_cx")
        self.pushButton_adtFolder = QtWidgets.QPushButton(rescoreVinaDialog)
        self.pushButton_adtFolder.setGeometry(QtCore.QRect(382, 70, 86, 21))
        self.pushButton_adtFolder.setObjectName("pushButton_adtFolder")
        self.label_exec = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_exec.setGeometry(QtCore.QRect(20, 40, 91, 20))
        self.label_exec.setObjectName("label_exec")
        self.pushButton_exec = QtWidgets.QPushButton(rescoreVinaDialog)
        self.pushButton_exec.setGeometry(QtCore.QRect(382, 40, 86, 21))
        self.pushButton_exec.setObjectName("pushButton_exec")
        self.textBrowser_vinaExec = QtWidgets.QTextBrowser(rescoreVinaDialog)
        self.textBrowser_vinaExec.setGeometry(QtCore.QRect(120, 40, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_vinaExec.setFont(font)
        self.textBrowser_vinaExec.setObjectName("textBrowser_vinaExec")
        self.line = QtWidgets.QFrame(rescoreVinaDialog)
        self.line.setGeometry(QtCore.QRect(200, 10, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(rescoreVinaDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 230, 461, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_6 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 41, 26))
        self.label_6.setObjectName("label_6")
        self.label_exec_2 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_exec_2.setGeometry(QtCore.QRect(20, 70, 91, 20))
        self.label_exec_2.setObjectName("label_exec_2")
        self.pushButton_cancel = QtWidgets.QPushButton(rescoreVinaDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(260, 250, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_5 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 41, 26))
        self.label_5.setObjectName("label_5")
        self.pushButton_ok = QtWidgets.QPushButton(rescoreVinaDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(130, 250, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.line_2 = QtWidgets.QFrame(rescoreVinaDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 211))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_8.setGeometry(QtCore.QRect(270, 200, 41, 26))
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 41, 26))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(rescoreVinaDialog)
        self.label_3.setGeometry(QtCore.QRect(70, 107, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_cy = QtWidgets.QDoubleSpinBox(rescoreVinaDialog)
        self.doubleSpinBox_cy.setGeometry(QtCore.QRect(80, 170, 131, 27))
        self.doubleSpinBox_cy.setDecimals(3)
        self.doubleSpinBox_cy.setMinimum(-10000.0)
        self.doubleSpinBox_cy.setMaximum(10000.0)
        self.doubleSpinBox_cy.setObjectName("doubleSpinBox_cy")
        self.doubleSpinBox_cz = QtWidgets.QDoubleSpinBox(rescoreVinaDialog)
        self.doubleSpinBox_cz.setGeometry(QtCore.QRect(80, 200, 131, 27))
        self.doubleSpinBox_cz.setDecimals(3)
        self.doubleSpinBox_cz.setMinimum(-10000.0)
        self.doubleSpinBox_cz.setMaximum(10000.0)
        self.doubleSpinBox_cz.setObjectName("doubleSpinBox_cz")
        self.label = QtWidgets.QLabel(rescoreVinaDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox_sy = QtWidgets.QSpinBox(rescoreVinaDialog)
        self.spinBox_sy.setGeometry(QtCore.QRect(310, 170, 101, 27))
        self.spinBox_sy.setMinimum(1)
        self.spinBox_sy.setMaximum(10000)
        self.spinBox_sy.setProperty("value", 40)
        self.spinBox_sy.setObjectName("spinBox_sy")
        self.spinBox_sz = QtWidgets.QSpinBox(rescoreVinaDialog)
        self.spinBox_sz.setGeometry(QtCore.QRect(310, 200, 101, 27))
        self.spinBox_sz.setMinimum(1)
        self.spinBox_sz.setMaximum(10000)
        self.spinBox_sz.setProperty("value", 40)
        self.spinBox_sz.setObjectName("spinBox_sz")
        self.spinBox_sx = QtWidgets.QSpinBox(rescoreVinaDialog)
        self.spinBox_sx.setGeometry(QtCore.QRect(310, 140, 101, 27))
        self.spinBox_sx.setMinimum(1)
        self.spinBox_sx.setMaximum(10000)
        self.spinBox_sx.setProperty("value", 40)
        self.spinBox_sx.setObjectName("spinBox_sx")

        self.retranslateUi(rescoreVinaDialog)
        QtCore.QMetaObject.connectSlotsByName(rescoreVinaDialog)

    def retranslateUi(self, rescoreVinaDialog):
        _translate = QtCore.QCoreApplication.translate
        rescoreVinaDialog.setWindowTitle(_translate("rescoreVinaDialog", "AutoDock Vina Rescoring Parameters"))
        self.label_9.setText(_translate("rescoreVinaDialog", "Y"))
        self.label_7.setText(_translate("rescoreVinaDialog", "X"))
        self.label_4.setText(_translate("rescoreVinaDialog", "Size of the grid"))
        self.textBrowser_adtFolder.setToolTip(_translate("rescoreVinaDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.pushButton_adtFolder.setToolTip(_translate("rescoreVinaDialog", "<html><head/><body><p>Folder containing python scripts to convert receptor and ligand files in PDBQT format.</p><p>Usually contained in \'MGLTools-{<span style=\" font-style:italic;\">version</span>}/MGLToolsPckgs/\' directory.</p></body></html>"))
        self.pushButton_adtFolder.setText(_translate("rescoreVinaDialog", "Browse"))
        self.label_exec.setText(_translate("rescoreVinaDialog", "Vina Executable"))
        self.pushButton_exec.setText(_translate("rescoreVinaDialog", "Browse"))
        self.label_6.setText(_translate("rescoreVinaDialog", "Z"))
        self.label_exec_2.setText(_translate("rescoreVinaDialog", "AutoDockTools"))
        self.pushButton_cancel.setText(_translate("rescoreVinaDialog", "Cancel"))
        self.label_5.setText(_translate("rescoreVinaDialog", "Y"))
        self.pushButton_ok.setText(_translate("rescoreVinaDialog", "Ok"))
        self.label_8.setText(_translate("rescoreVinaDialog", "Z"))
        self.label_2.setText(_translate("rescoreVinaDialog", "X"))
        self.label_3.setText(_translate("rescoreVinaDialog", "Center of the grid"))
        self.label.setText(_translate("rescoreVinaDialog", "Rescoring with AutoDock Vina"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rescoreVinaDialog = QtWidgets.QDialog()
    ui = Ui_rescoreVinaDialog()
    ui.setupUi(rescoreVinaDialog)
    rescoreVinaDialog.show()
    sys.exit(app.exec_())

