# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/Dropbox/work/ChemFlow/GUI/runPBS/runpbsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RunPBSDialog(object):
    def setupUi(self, RunPBSDialog):
        RunPBSDialog.setObjectName("RunPBSDialog")
        RunPBSDialog.resize(292, 199)
        self.label = QtWidgets.QLabel(RunPBSDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox_nodes = QtWidgets.QSpinBox(RunPBSDialog)
        self.spinBox_nodes.setGeometry(QtCore.QRect(170, 40, 61, 27))
        self.spinBox_nodes.setMinimum(1)
        self.spinBox_nodes.setMaximum(10000)
        self.spinBox_nodes.setObjectName("spinBox_nodes")
        self.line_3 = QtWidgets.QFrame(RunPBSDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_cancel = QtWidgets.QPushButton(RunPBSDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(160, 160, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_2 = QtWidgets.QLabel(RunPBSDialog)
        self.label_2.setGeometry(QtCore.QRect(39, 43, 121, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(RunPBSDialog)
        self.line.setGeometry(QtCore.QRect(120, 10, 161, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(RunPBSDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_ok = QtWidgets.QPushButton(RunPBSDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(40, 160, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.spinBox_ppn = QtWidgets.QSpinBox(RunPBSDialog)
        self.spinBox_ppn.setGeometry(QtCore.QRect(170, 74, 61, 27))
        self.spinBox_ppn.setMinimum(1)
        self.spinBox_ppn.setMaximum(1024)
        self.spinBox_ppn.setObjectName("spinBox_ppn")
        self.label_3 = QtWidgets.QLabel(RunPBSDialog)
        self.label_3.setGeometry(QtCore.QRect(19, 80, 141, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(RunPBSDialog)
        self.label_4.setGeometry(QtCore.QRect(18, 110, 141, 27))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(RunPBSDialog)
        self.comboBox.setGeometry(QtCore.QRect(170, 110, 94, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(RunPBSDialog)
        QtCore.QMetaObject.connectSlotsByName(RunPBSDialog)

    def retranslateUi(self, RunPBSDialog):
        _translate = QtCore.QCoreApplication.translate
        RunPBSDialog.setWindowTitle(_translate("RunPBSDialog", "PBS Run Parameters"))
        self.label.setText(_translate("RunPBSDialog", "Run with PBS"))
        self.pushButton_cancel.setText(_translate("RunPBSDialog", "Cancel"))
        self.label_2.setText(_translate("RunPBSDialog", "Number of nodes"))
        self.pushButton_ok.setText(_translate("RunPBSDialog", "Ok"))
        self.label_3.setText(_translate("RunPBSDialog", "Processors per node"))
        self.label_4.setText(_translate("RunPBSDialog", "Walltime (HH:mm:ss)"))
        self.comboBox.setCurrentText(_translate("RunPBSDialog", "00:30:00"))
        self.comboBox.setItemText(0, _translate("RunPBSDialog", "00:30:00"))
        self.comboBox.setItemText(1, _translate("RunPBSDialog", "01:00:00"))
        self.comboBox.setItemText(2, _translate("RunPBSDialog", "02:00:00"))
        self.comboBox.setItemText(3, _translate("RunPBSDialog", "05:00:00"))
        self.comboBox.setItemText(4, _translate("RunPBSDialog", "08:00:00"))
        self.comboBox.setItemText(5, _translate("RunPBSDialog", "10:00:00"))
        self.comboBox.setItemText(6, _translate("RunPBSDialog", "12:00:00"))
        self.comboBox.setItemText(7, _translate("RunPBSDialog", "15:00:00"))
        self.comboBox.setItemText(8, _translate("RunPBSDialog", "18:00:00"))
        self.comboBox.setItemText(9, _translate("RunPBSDialog", "20:00:00"))
        self.comboBox.setItemText(10, _translate("RunPBSDialog", "24:00:00"))
        self.comboBox.setItemText(11, _translate("RunPBSDialog", "30:00:00"))
        self.comboBox.setItemText(12, _translate("RunPBSDialog", "36:00:00"))
        self.comboBox.setItemText(13, _translate("RunPBSDialog", "40:00:00"))
        self.comboBox.setItemText(14, _translate("RunPBSDialog", "48:00:00"))
        self.comboBox.setItemText(15, _translate("RunPBSDialog", "54:00:00"))
        self.comboBox.setItemText(16, _translate("RunPBSDialog", "60:00:00"))
        self.comboBox.setItemText(17, _translate("RunPBSDialog", "72:00:00"))
        self.comboBox.setItemText(18, _translate("RunPBSDialog", "84:00:00"))
        self.comboBox.setItemText(19, _translate("RunPBSDialog", "96:00:00"))
        self.comboBox.setItemText(20, _translate("RunPBSDialog", "120:00:00"))
        self.comboBox.setItemText(21, _translate("RunPBSDialog", "144:00:00"))
        self.comboBox.setItemText(22, _translate("RunPBSDialog", "168:00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RunPBSDialog = QtWidgets.QDialog()
    ui = Ui_RunPBSDialog()
    ui.setupUi(RunPBSDialog)
    RunPBSDialog.show()
    sys.exit(app.exec_())

