# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/software/ChemFlow/ChemFlow/src/GUI/qt_creator/docking_vina.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockingVina(object):
    def setupUi(self, DockingVina):
        DockingVina.setObjectName("DockingVina")
        DockingVina.resize(434, 263)
        self.spinBox_sz = QtWidgets.QSpinBox(DockingVina)
        self.spinBox_sz.setGeometry(QtCore.QRect(300, 165, 101, 27))
        self.spinBox_sz.setMinimum(1)
        self.spinBox_sz.setMaximum(10000)
        self.spinBox_sz.setProperty("value", 8)
        self.spinBox_sz.setObjectName("spinBox_sz")
        self.label_3 = QtWidgets.QLabel(DockingVina)
        self.label_3.setGeometry(QtCore.QRect(42, 73, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(DockingVina)
        self.label_10.setGeometry(QtCore.QRect(37, 35, 111, 20))
        self.label_10.setObjectName("label_10")
        self.doubleSpinBox_energyRange = QtWidgets.QDoubleSpinBox(DockingVina)
        self.doubleSpinBox_energyRange.setGeometry(QtCore.QRect(344, 32, 65, 27))
        self.doubleSpinBox_energyRange.setProperty("value", 3.0)
        self.doubleSpinBox_energyRange.setObjectName("doubleSpinBox_energyRange")
        self.doubleSpinBox_cz = QtWidgets.QDoubleSpinBox(DockingVina)
        self.doubleSpinBox_cz.setGeometry(QtCore.QRect(70, 165, 131, 27))
        self.doubleSpinBox_cz.setDecimals(3)
        self.doubleSpinBox_cz.setMinimum(-10000.0)
        self.doubleSpinBox_cz.setMaximum(10000.0)
        self.doubleSpinBox_cz.setObjectName("doubleSpinBox_cz")
        self.label = QtWidgets.QLabel(DockingVina)
        self.label.setGeometry(QtCore.QRect(13, 10, 211, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_ok = QtWidgets.QPushButton(DockingVina)
        self.pushButton_ok.setGeometry(QtCore.QRect(110, 215, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label_2 = QtWidgets.QLabel(DockingVina)
        self.label_2.setGeometry(QtCore.QRect(30, 105, 41, 26))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(DockingVina)
        self.label_4.setGeometry(QtCore.QRect(267, 73, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(DockingVina)
        self.label_11.setGeometry(QtCore.QRect(250, 35, 91, 20))
        self.label_11.setObjectName("label_11")
        self.spinBox_sx = QtWidgets.QSpinBox(DockingVina)
        self.spinBox_sx.setGeometry(QtCore.QRect(300, 105, 101, 27))
        self.spinBox_sx.setMinimum(1)
        self.spinBox_sx.setMaximum(10000)
        self.spinBox_sx.setProperty("value", 8)
        self.spinBox_sx.setObjectName("spinBox_sx")
        self.doubleSpinBox_cy = QtWidgets.QDoubleSpinBox(DockingVina)
        self.doubleSpinBox_cy.setGeometry(QtCore.QRect(70, 135, 131, 27))
        self.doubleSpinBox_cy.setDecimals(3)
        self.doubleSpinBox_cy.setMinimum(-10000.0)
        self.doubleSpinBox_cy.setMaximum(10000.0)
        self.doubleSpinBox_cy.setObjectName("doubleSpinBox_cy")
        self.label_6 = QtWidgets.QLabel(DockingVina)
        self.label_6.setGeometry(QtCore.QRect(30, 165, 41, 26))
        self.label_6.setObjectName("label_6")
        self.doubleSpinBox_cx = QtWidgets.QDoubleSpinBox(DockingVina)
        self.doubleSpinBox_cx.setGeometry(QtCore.QRect(70, 105, 131, 27))
        self.doubleSpinBox_cx.setDecimals(3)
        self.doubleSpinBox_cx.setMinimum(-10000.0)
        self.doubleSpinBox_cx.setMaximum(10000.0)
        self.doubleSpinBox_cx.setObjectName("doubleSpinBox_cx")
        self.spinBox_sy = QtWidgets.QSpinBox(DockingVina)
        self.spinBox_sy.setGeometry(QtCore.QRect(300, 135, 101, 27))
        self.spinBox_sy.setMinimum(1)
        self.spinBox_sy.setMaximum(10000)
        self.spinBox_sy.setProperty("value", 8)
        self.spinBox_sy.setObjectName("spinBox_sy")
        self.label_7 = QtWidgets.QLabel(DockingVina)
        self.label_7.setGeometry(QtCore.QRect(260, 105, 41, 26))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(DockingVina)
        self.label_9.setGeometry(QtCore.QRect(260, 135, 41, 26))
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(DockingVina)
        self.label_5.setGeometry(QtCore.QRect(30, 135, 41, 26))
        self.label_5.setObjectName("label_5")
        self.spinBox_exhaustiveness = QtWidgets.QSpinBox(DockingVina)
        self.spinBox_exhaustiveness.setGeometry(QtCore.QRect(147, 32, 51, 27))
        self.spinBox_exhaustiveness.setMinimum(1)
        self.spinBox_exhaustiveness.setProperty("value", 8)
        self.spinBox_exhaustiveness.setObjectName("spinBox_exhaustiveness")
        self.line_4 = QtWidgets.QFrame(DockingVina)
        self.line_4.setGeometry(QtCore.QRect(220, 75, 20, 131))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_cancel = QtWidgets.QPushButton(DockingVina)
        self.pushButton_cancel.setGeometry(QtCore.QRect(240, 215, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_8 = QtWidgets.QLabel(DockingVina)
        self.label_8.setGeometry(QtCore.QRect(260, 165, 41, 26))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(DockingVina)
        QtCore.QMetaObject.connectSlotsByName(DockingVina)

    def retranslateUi(self, DockingVina):
        _translate = QtCore.QCoreApplication.translate
        DockingVina.setWindowTitle(_translate("DockingVina", "Docking - Vina"))
        self.label_3.setText(_translate("DockingVina", "Center of the grid"))
        self.label_10.setText(_translate("DockingVina", "Exhaustiveness"))
        self.doubleSpinBox_energyRange.setToolTip(_translate("DockingVina", "<html><head/><body><p>Maximum energy difference between the best binding mode and the worst one displayed (kcal/mol)</p></body></html>"))
        self.label.setText(_translate("DockingVina", "Docking with AutoDock Vina"))
        self.pushButton_ok.setText(_translate("DockingVina", "Ok"))
        self.label_2.setText(_translate("DockingVina", "X"))
        self.label_4.setText(_translate("DockingVina", "Size of the grid"))
        self.label_11.setText(_translate("DockingVina", "Energy range"))
        self.label_6.setText(_translate("DockingVina", "Z"))
        self.label_7.setText(_translate("DockingVina", "X"))
        self.label_9.setText(_translate("DockingVina", "Y"))
        self.label_5.setText(_translate("DockingVina", "Y"))
        self.pushButton_cancel.setText(_translate("DockingVina", "Cancel"))
        self.label_8.setText(_translate("DockingVina", "Z"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DockingVina = QtWidgets.QWidget()
    ui = Ui_DockingVina()
    ui.setupUi(DockingVina)
    DockingVina.show()
    sys.exit(app.exec_())

