# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/software/ChemFlow/ChemFlow/src/GUI/qt_creator/mmgbsa.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScoringMmgbsa(object):
    def setupUi(self, ScoringMmgbsa):
        ScoringMmgbsa.setObjectName("ScoringMmgbsa")
        ScoringMmgbsa.resize(400, 318)
        self.checkBox_run_only = QtWidgets.QCheckBox(ScoringMmgbsa)
        self.checkBox_run_only.setGeometry(QtCore.QRect(160, 243, 101, 22))
        self.checkBox_run_only.setObjectName("checkBox_run_only")
        self.checkBox_write_only = QtWidgets.QCheckBox(ScoringMmgbsa)
        self.checkBox_write_only.setGeometry(QtCore.QRect(40, 243, 111, 22))
        self.checkBox_write_only.setObjectName("checkBox_write_only")
        self.comboBox_charges = QtWidgets.QComboBox(ScoringMmgbsa)
        self.comboBox_charges.setGeometry(QtCore.QRect(113, 70, 111, 26))
        self.comboBox_charges.setObjectName("comboBox_charges")
        self.comboBox_charges.addItem("")
        self.comboBox_charges.addItem("")
        self.comboBox_charges.addItem("")
        self.label_15 = QtWidgets.QLabel(ScoringMmgbsa)
        self.label_15.setGeometry(QtCore.QRect(29, 72, 71, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(ScoringMmgbsa)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_cancel = QtWidgets.QPushButton(ScoringMmgbsa)
        self.pushButton_cancel.setGeometry(QtCore.QRect(220, 280, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_ok = QtWidgets.QPushButton(ScoringMmgbsa)
        self.pushButton_ok.setGeometry(QtCore.QRect(90, 280, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label_2 = QtWidgets.QLabel(ScoringMmgbsa)
        self.label_2.setGeometry(QtCore.QRect(21, 217, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ScoringMmgbsa)
        self.label_3.setGeometry(QtCore.QRect(20, 44, 161, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ScoringMmgbsa)
        self.label_4.setGeometry(QtCore.QRect(22, 105, 161, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_maxcyc = QtWidgets.QSpinBox(ScoringMmgbsa)
        self.spinBox_maxcyc.setGeometry(QtCore.QRect(113, 160, 91, 27))
        self.spinBox_maxcyc.setSuffix("")
        self.spinBox_maxcyc.setMinimum(1)
        self.spinBox_maxcyc.setMaximum(99999)
        self.spinBox_maxcyc.setSingleStep(100)
        self.spinBox_maxcyc.setProperty("value", 1000)
        self.spinBox_maxcyc.setDisplayIntegerBase(10)
        self.spinBox_maxcyc.setObjectName("spinBox_maxcyc")
        self.label_5 = QtWidgets.QLabel(ScoringMmgbsa)
        self.label_5.setGeometry(QtCore.QRect(19, 162, 81, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.radioButton_implicit = QtWidgets.QRadioButton(ScoringMmgbsa)
        self.radioButton_implicit.setGeometry(QtCore.QRect(112, 132, 117, 22))
        self.radioButton_implicit.setChecked(True)
        self.radioButton_implicit.setObjectName("radioButton_implicit")
        self.radioButton_explicit = QtWidgets.QRadioButton(ScoringMmgbsa)
        self.radioButton_explicit.setGeometry(QtCore.QRect(212, 132, 117, 22))
        self.radioButton_explicit.setObjectName("radioButton_explicit")
        self.label_6 = QtWidgets.QLabel(ScoringMmgbsa)
        self.label_6.setGeometry(QtCore.QRect(32, 134, 67, 17))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.checkBox_MD = QtWidgets.QCheckBox(ScoringMmgbsa)
        self.checkBox_MD.setGeometry(QtCore.QRect(111, 196, 97, 22))
        self.checkBox_MD.setObjectName("checkBox_MD")

        self.retranslateUi(ScoringMmgbsa)
        QtCore.QMetaObject.connectSlotsByName(ScoringMmgbsa)
        ScoringMmgbsa.setTabOrder(self.comboBox_charges, self.radioButton_implicit)
        ScoringMmgbsa.setTabOrder(self.radioButton_implicit, self.radioButton_explicit)
        ScoringMmgbsa.setTabOrder(self.radioButton_explicit, self.spinBox_maxcyc)
        ScoringMmgbsa.setTabOrder(self.spinBox_maxcyc, self.checkBox_MD)
        ScoringMmgbsa.setTabOrder(self.checkBox_MD, self.checkBox_write_only)
        ScoringMmgbsa.setTabOrder(self.checkBox_write_only, self.checkBox_run_only)
        ScoringMmgbsa.setTabOrder(self.checkBox_run_only, self.pushButton_ok)
        ScoringMmgbsa.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, ScoringMmgbsa):
        _translate = QtCore.QCoreApplication.translate
        ScoringMmgbsa.setWindowTitle(_translate("ScoringMmgbsa", "Rescoring - MM/GBSA"))
        self.checkBox_run_only.setToolTip(_translate("ScoringMmgbsa", "Run using the ScoreFlow.run.template file"))
        self.checkBox_run_only.setText(_translate("ScoringMmgbsa", "Run only"))
        self.checkBox_write_only.setToolTip(_translate("ScoringMmgbsa", "Write a template file (ScoreFlow.run.template) command without running"))
        self.checkBox_write_only.setText(_translate("ScoringMmgbsa", "Write only"))
        self.comboBox_charges.setItemText(0, _translate("ScoringMmgbsa", "Gasteiger"))
        self.comboBox_charges.setItemText(1, _translate("ScoringMmgbsa", "AM1-BCC"))
        self.comboBox_charges.setItemText(2, _translate("ScoringMmgbsa", "RESP"))
        self.label_15.setText(_translate("ScoringMmgbsa", "Charges"))
        self.label.setText(_translate("ScoringMmgbsa", "Rescoring with MM/GBSA"))
        self.pushButton_cancel.setText(_translate("ScoringMmgbsa", "Cancel"))
        self.pushButton_ok.setText(_translate("ScoringMmgbsa", "Ok"))
        self.label_2.setText(_translate("ScoringMmgbsa", "Execution"))
        self.label_3.setText(_translate("ScoringMmgbsa", "Ligands parameters"))
        self.label_4.setText(_translate("ScoringMmgbsa", "Simulation protocol"))
        self.spinBox_maxcyc.setToolTip(_translate("ScoringMmgbsa", "<html><head/><body><p>Maximum number of energy minimization steps <span style=\" font-weight:600;\">for implicit solvent simulations</span></p></body></html>"))
        self.label_5.setText(_translate("ScoringMmgbsa", "Max cycles"))
        self.radioButton_implicit.setText(_translate("ScoringMmgbsa", "Implicit"))
        self.radioButton_explicit.setText(_translate("ScoringMmgbsa", "Explicit"))
        self.label_6.setText(_translate("ScoringMmgbsa", "Solvent"))
        self.checkBox_MD.setToolTip(_translate("ScoringMmgbsa", "Run a Molecular Dynamics simulation"))
        self.checkBox_MD.setText(_translate("ScoringMmgbsa", "MD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScoringMmgbsa = QtWidgets.QWidget()
    ui = Ui_ScoringMmgbsa()
    ui.setupUi(ScoringMmgbsa)
    ScoringMmgbsa.show()
    sys.exit(app.exec_())

