# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/software/ChemFlow/ChemFlow/src/GUI/qt_creator/scoring_vina.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScoringVina(object):
    def setupUi(self, ScoringVina):
        ScoringVina.setObjectName("ScoringVina")
        ScoringVina.resize(434, 272)
        self.label_3 = QtWidgets.QLabel(ScoringVina)
        self.label_3.setGeometry(QtCore.QRect(42, 39, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_cz = QtWidgets.QDoubleSpinBox(ScoringVina)
        self.doubleSpinBox_cz.setGeometry(QtCore.QRect(70, 131, 131, 27))
        self.doubleSpinBox_cz.setDecimals(3)
        self.doubleSpinBox_cz.setMinimum(-10000.0)
        self.doubleSpinBox_cz.setMaximum(10000.0)
        self.doubleSpinBox_cz.setObjectName("doubleSpinBox_cz")
        self.spinBox_sx = QtWidgets.QSpinBox(ScoringVina)
        self.spinBox_sx.setGeometry(QtCore.QRect(300, 71, 101, 27))
        self.spinBox_sx.setMinimum(1)
        self.spinBox_sx.setMaximum(10000)
        self.spinBox_sx.setProperty("value", 8)
        self.spinBox_sx.setObjectName("spinBox_sx")
        self.label_6 = QtWidgets.QLabel(ScoringVina)
        self.label_6.setGeometry(QtCore.QRect(30, 131, 41, 26))
        self.label_6.setObjectName("label_6")
        self.spinBox_sz = QtWidgets.QSpinBox(ScoringVina)
        self.spinBox_sz.setGeometry(QtCore.QRect(300, 131, 101, 27))
        self.spinBox_sz.setMinimum(1)
        self.spinBox_sz.setMaximum(10000)
        self.spinBox_sz.setProperty("value", 8)
        self.spinBox_sz.setObjectName("spinBox_sz")
        self.doubleSpinBox_cx = QtWidgets.QDoubleSpinBox(ScoringVina)
        self.doubleSpinBox_cx.setGeometry(QtCore.QRect(70, 71, 131, 27))
        self.doubleSpinBox_cx.setDecimals(3)
        self.doubleSpinBox_cx.setMinimum(-10000.0)
        self.doubleSpinBox_cx.setMaximum(10000.0)
        self.doubleSpinBox_cx.setObjectName("doubleSpinBox_cx")
        self.label_9 = QtWidgets.QLabel(ScoringVina)
        self.label_9.setGeometry(QtCore.QRect(260, 101, 41, 26))
        self.label_9.setObjectName("label_9")
        self.pushButton_cancel = QtWidgets.QPushButton(ScoringVina)
        self.pushButton_cancel.setGeometry(QtCore.QRect(240, 230, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_7 = QtWidgets.QLabel(ScoringVina)
        self.label_7.setGeometry(QtCore.QRect(260, 71, 41, 26))
        self.label_7.setObjectName("label_7")
        self.spinBox_sy = QtWidgets.QSpinBox(ScoringVina)
        self.spinBox_sy.setGeometry(QtCore.QRect(300, 101, 101, 27))
        self.spinBox_sy.setMinimum(1)
        self.spinBox_sy.setMaximum(10000)
        self.spinBox_sy.setProperty("value", 8)
        self.spinBox_sy.setObjectName("spinBox_sy")
        self.doubleSpinBox_cy = QtWidgets.QDoubleSpinBox(ScoringVina)
        self.doubleSpinBox_cy.setGeometry(QtCore.QRect(70, 101, 131, 27))
        self.doubleSpinBox_cy.setDecimals(3)
        self.doubleSpinBox_cy.setMinimum(-10000.0)
        self.doubleSpinBox_cy.setMaximum(10000.0)
        self.doubleSpinBox_cy.setObjectName("doubleSpinBox_cy")
        self.label_5 = QtWidgets.QLabel(ScoringVina)
        self.label_5.setGeometry(QtCore.QRect(30, 101, 41, 26))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(ScoringVina)
        self.label.setGeometry(QtCore.QRect(13, 10, 231, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(ScoringVina)
        self.label_4.setGeometry(QtCore.QRect(267, 39, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(ScoringVina)
        self.label_2.setGeometry(QtCore.QRect(30, 71, 41, 26))
        self.label_2.setObjectName("label_2")
        self.pushButton_ok = QtWidgets.QPushButton(ScoringVina)
        self.pushButton_ok.setGeometry(QtCore.QRect(110, 230, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.line_4 = QtWidgets.QFrame(ScoringVina)
        self.line_4.setGeometry(QtCore.QRect(210, 41, 20, 131))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_8 = QtWidgets.QLabel(ScoringVina)
        self.label_8.setGeometry(QtCore.QRect(260, 131, 41, 26))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(ScoringVina)
        self.label_10.setGeometry(QtCore.QRect(30, 170, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.radioButton_local = QtWidgets.QRadioButton(ScoringVina)
        self.radioButton_local.setGeometry(QtCore.QRect(50, 196, 117, 22))
        self.radioButton_local.setChecked(True)
        self.radioButton_local.setObjectName("radioButton_local")
        self.radioButton_score = QtWidgets.QRadioButton(ScoringVina)
        self.radioButton_score.setGeometry(QtCore.QRect(190, 196, 117, 22))
        self.radioButton_score.setObjectName("radioButton_score")

        self.retranslateUi(ScoringVina)
        QtCore.QMetaObject.connectSlotsByName(ScoringVina)
        ScoringVina.setTabOrder(self.doubleSpinBox_cx, self.doubleSpinBox_cy)
        ScoringVina.setTabOrder(self.doubleSpinBox_cy, self.doubleSpinBox_cz)
        ScoringVina.setTabOrder(self.doubleSpinBox_cz, self.spinBox_sx)
        ScoringVina.setTabOrder(self.spinBox_sx, self.spinBox_sy)
        ScoringVina.setTabOrder(self.spinBox_sy, self.spinBox_sz)
        ScoringVina.setTabOrder(self.spinBox_sz, self.pushButton_ok)
        ScoringVina.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, ScoringVina):
        _translate = QtCore.QCoreApplication.translate
        ScoringVina.setWindowTitle(_translate("ScoringVina", "Rescoring - Vina"))
        self.label_3.setText(_translate("ScoringVina", "Center of the grid"))
        self.label_6.setText(_translate("ScoringVina", "Z"))
        self.label_9.setText(_translate("ScoringVina", "Y"))
        self.pushButton_cancel.setText(_translate("ScoringVina", "Cancel"))
        self.label_7.setText(_translate("ScoringVina", "X"))
        self.label_5.setText(_translate("ScoringVina", "Y"))
        self.label.setText(_translate("ScoringVina", "Rescoring with AutoDock Vina"))
        self.label_4.setText(_translate("ScoringVina", "Size of the grid"))
        self.label_2.setText(_translate("ScoringVina", "X"))
        self.pushButton_ok.setText(_translate("ScoringVina", "Ok"))
        self.label_8.setText(_translate("ScoringVina", "Z"))
        self.label_10.setText(_translate("ScoringVina", "Rescoring mode"))
        self.radioButton_local.setToolTip(_translate("ScoringVina", "<html><head/><body><p>Perform a local search (minimization) prior to rescoring</p></body></html>"))
        self.radioButton_local.setText(_translate("ScoringVina", "Local only"))
        self.radioButton_score.setToolTip(_translate("ScoringVina", "Recore the input conformation"))
        self.radioButton_score.setText(_translate("ScoringVina", "Score only"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScoringVina = QtWidgets.QWidget()
    ui = Ui_ScoringVina()
    ui.setupUi(ScoringVina)
    ScoringVina.show()
    sys.exit(app.exec_())

