# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cedric/software/ChemFlow/ChemFlow/src/GUI/qt_creator/tool_smiles_to_3d.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ToolSmilesTo3d(object):
    def setupUi(self, ToolSmilesTo3d):
        ToolSmilesTo3d.setObjectName("ToolSmilesTo3d")
        ToolSmilesTo3d.resize(480, 499)
        self.label = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_input = QtWidgets.QLineEdit(ToolSmilesTo3d)
        self.lineEdit_input.setGeometry(QtCore.QRect(152, 57, 212, 20))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.pushButton_input = QtWidgets.QPushButton(ToolSmilesTo3d)
        self.pushButton_input.setGeometry(QtCore.QRect(368, 55, 86, 23))
        self.pushButton_input.setObjectName("pushButton_input")
        self.label_rec = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_rec.setGeometry(QtCore.QRect(40, 36, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rec.setFont(font)
        self.label_rec.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rec.setObjectName("label_rec")
        self.pushButton_ok = QtWidgets.QPushButton(ToolSmilesTo3d)
        self.pushButton_ok.setGeometry(QtCore.QRect(131, 461, 86, 29))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(ToolSmilesTo3d)
        self.pushButton_cancel.setGeometry(QtCore.QRect(261, 461, 86, 29))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_2 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_2.setGeometry(QtCore.QRect(60, 59, 67, 17))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.spinBox_smiles_col = QtWidgets.QSpinBox(ToolSmilesTo3d)
        self.spinBox_smiles_col.setGeometry(QtCore.QRect(150, 83, 48, 27))
        self.spinBox_smiles_col.setMinimum(1)
        self.spinBox_smiles_col.setProperty("value", 1)
        self.spinBox_smiles_col.setObjectName("spinBox_smiles_col")
        self.label_3 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_3.setGeometry(QtCore.QRect(16, 86, 111, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_4.setGeometry(QtCore.QRect(16, 116, 111, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.spinBox_names_col = QtWidgets.QSpinBox(ToolSmilesTo3d)
        self.spinBox_names_col.setGeometry(QtCore.QRect(150, 113, 48, 27))
        self.spinBox_names_col.setMinimum(1)
        self.spinBox_names_col.setProperty("value", 2)
        self.spinBox_names_col.setObjectName("spinBox_names_col")
        self.label_5 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_5.setGeometry(QtCore.QRect(60, 149, 67, 17))
        self.label_5.setObjectName("label_5")
        self.comboBox_delimiter = QtWidgets.QComboBox(ToolSmilesTo3d)
        self.comboBox_delimiter.setGeometry(QtCore.QRect(150, 143, 85, 27))
        self.comboBox_delimiter.setObjectName("comboBox_delimiter")
        self.comboBox_delimiter.addItem("")
        self.comboBox_delimiter.addItem("")
        self.comboBox_delimiter.addItem("")
        self.comboBox_delimiter.addItem("")
        self.comboBox_delimiter.addItem("")
        self.checkBox_header = QtWidgets.QCheckBox(ToolSmilesTo3d)
        self.checkBox_header.setGeometry(QtCore.QRect(150, 174, 171, 22))
        self.checkBox_header.setObjectName("checkBox_header")
        self.label_6 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_6.setGeometry(QtCore.QRect(40, 214, 67, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_output = QtWidgets.QLineEdit(ToolSmilesTo3d)
        self.lineEdit_output.setGeometry(QtCore.QRect(152, 236, 301, 20))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.label_7 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_7.setGeometry(QtCore.QRect(59, 240, 67, 17))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.checkBox_hydrogen = QtWidgets.QCheckBox(ToolSmilesTo3d)
        self.checkBox_hydrogen.setGeometry(QtCore.QRect(150, 265, 221, 22))
        self.checkBox_hydrogen.setObjectName("checkBox_hydrogen")
        self.checkBox_verbose = QtWidgets.QCheckBox(ToolSmilesTo3d)
        self.checkBox_verbose.setGeometry(QtCore.QRect(150, 291, 221, 22))
        self.checkBox_verbose.setObjectName("checkBox_verbose")
        self.label_8 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_8.setGeometry(QtCore.QRect(40, 367, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.comboBox_method = QtWidgets.QComboBox(ToolSmilesTo3d)
        self.comboBox_method.setGeometry(QtCore.QRect(150, 324, 85, 27))
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.label_9 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_9.setGeometry(QtCore.QRect(40, 330, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBox_nthreads = QtWidgets.QSpinBox(ToolSmilesTo3d)
        self.spinBox_nthreads.setGeometry(QtCore.QRect(150, 390, 48, 27))
        self.spinBox_nthreads.setMinimum(1)
        self.spinBox_nthreads.setProperty("value", 1)
        self.spinBox_nthreads.setObjectName("spinBox_nthreads")
        self.label_10 = QtWidgets.QLabel(ToolSmilesTo3d)
        self.label_10.setGeometry(QtCore.QRect(25, 394, 101, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.checkBox_mpi = QtWidgets.QCheckBox(ToolSmilesTo3d)
        self.checkBox_mpi.setGeometry(QtCore.QRect(150, 425, 131, 22))
        self.checkBox_mpi.setObjectName("checkBox_mpi")

        self.retranslateUi(ToolSmilesTo3d)
        QtCore.QMetaObject.connectSlotsByName(ToolSmilesTo3d)

    def retranslateUi(self, ToolSmilesTo3d):
        _translate = QtCore.QCoreApplication.translate
        ToolSmilesTo3d.setWindowTitle(_translate("ToolSmilesTo3d", "SMILES to 3D"))
        self.label.setText(_translate("ToolSmilesTo3d", "SMILES to 3D"))
        self.lineEdit_input.setPlaceholderText(_translate("ToolSmilesTo3d", "Path to input SMILES file"))
        self.pushButton_input.setToolTip(_translate("ToolSmilesTo3d", "<html><head/><body><p>Text file containing one molecule in SMILES format per line.</p></body></html>"))
        self.pushButton_input.setText(_translate("ToolSmilesTo3d", "Browse"))
        self.label_rec.setText(_translate("ToolSmilesTo3d", "Input"))
        self.pushButton_ok.setText(_translate("ToolSmilesTo3d", "Ok"))
        self.pushButton_cancel.setText(_translate("ToolSmilesTo3d", "Cancel"))
        self.label_2.setText(_translate("ToolSmilesTo3d", "File"))
        self.spinBox_smiles_col.setToolTip(_translate("ToolSmilesTo3d", "<html><head/><body><p>Index of the column containing the SMILES</p></body></html>"))
        self.label_3.setText(_translate("ToolSmilesTo3d", "SMILES column"))
        self.label_4.setText(_translate("ToolSmilesTo3d", "Name column"))
        self.spinBox_names_col.setToolTip(_translate("ToolSmilesTo3d", "<html><head/><body><p>Index of the column containing the names of your molecules</p></body></html>"))
        self.label_5.setText(_translate("ToolSmilesTo3d", "Delimiter"))
        self.comboBox_delimiter.setItemText(0, _translate("ToolSmilesTo3d", "Tab"))
        self.comboBox_delimiter.setItemText(1, _translate("ToolSmilesTo3d", "Space"))
        self.comboBox_delimiter.setItemText(2, _translate("ToolSmilesTo3d", ","))
        self.comboBox_delimiter.setItemText(3, _translate("ToolSmilesTo3d", ";"))
        self.comboBox_delimiter.setItemText(4, _translate("ToolSmilesTo3d", ":"))
        self.checkBox_header.setText(_translate("ToolSmilesTo3d", "Fist line is a header"))
        self.label_6.setText(_translate("ToolSmilesTo3d", "Output"))
        self.lineEdit_output.setPlaceholderText(_translate("ToolSmilesTo3d", "Path to output SDF file"))
        self.label_7.setText(_translate("ToolSmilesTo3d", "File"))
        self.checkBox_hydrogen.setText(_translate("ToolSmilesTo3d", "Write all Hydrogen atoms"))
        self.checkBox_verbose.setToolTip(_translate("ToolSmilesTo3d", "<html><head/><body><p>Print additional information to the terminal</p></body></html>"))
        self.checkBox_verbose.setText(_translate("ToolSmilesTo3d", "Increase output verbosity"))
        self.label_8.setText(_translate("ToolSmilesTo3d", "Execution"))
        self.comboBox_method.setToolTip(_translate("ToolSmilesTo3d", "<html><head/><body><p>Method used to generate 3D conformations: </p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">UFF</span> : distance geometry + force field minimization with UFF</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">MMFF</span> : distance geometry + force field minimization with MMFF</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ETKDG </span>: distance geometry with experimental torsion angles knowledge from the CSD</li></ul></body></html>"))
        self.comboBox_method.setItemText(0, _translate("ToolSmilesTo3d", "ETKDG"))
        self.comboBox_method.setItemText(1, _translate("ToolSmilesTo3d", "MMFF"))
        self.comboBox_method.setItemText(2, _translate("ToolSmilesTo3d", "UFF"))
        self.label_9.setText(_translate("ToolSmilesTo3d", "Method"))
        self.spinBox_nthreads.setToolTip(_translate("ToolSmilesTo3d", "<html><head/><body><p>Number of threads used for the generation of conformations</p></body></html>"))
        self.label_10.setText(_translate("ToolSmilesTo3d", "CPU threads"))
        self.checkBox_mpi.setText(_translate("ToolSmilesTo3d", "Run with MPI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToolSmilesTo3d = QtWidgets.QWidget()
    ui = Ui_ToolSmilesTo3d()
    ui.setupUi(ToolSmilesTo3d)
    ToolSmilesTo3d.show()
    sys.exit(app.exec_())

